---
- hosts: media-box
  become: true
  tasks:
    - name: Download minikube binary
      get_url:
        url: "https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64"
        dest: "/tmp/minikube-linux-amd64"
        mode: '0755' # Make executable

    - name: Install minikube
      command:
        cmd: install /tmp/minikube-linux-amd64 /usr/local/bin/minikube

    - name: Remove temporary minikube binary
      file:
        path: "/tmp/minikube-linux-amd64"
        state: absent
